services:

  ctraid-telegram-bot:
    container_name: ctraid-bot-dev

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - SERVER_HOST=http://server:8000

    env_file:
      - .env

    command: sh ./start.dev.sh

    networks:
      - backend_ctraid-network

    develop:
      watch:
        - action: sync
          path: ./telegram_bot/
          target: /app/telegram_bot/

networks:
  backend_ctraid-network:
    external: true
